version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=happytails
      - POSTGRES_USER=happytails
      - POSTGRES_PASSWORD=happytails123
    configs:
      - source: db_init_script
        target: /docker-entrypoint-initdb.d/init-databases.sh
        mode: 0755
    volumes:
      - postgres-data-new:/var/lib/postgresql/data
    networks:
      - happytails-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/project-realm-realm.json:/opt/keycloak/data/import/project-realm-realm.json
    ports:
      - "8080:8080"
    networks:
      - happytails-network
    depends_on:
      - postgres

  django:
    image: happytails-django:latest
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-i8)8x40o(f&h5r0vbur#n&1g5sooyjpc-f8f^4%0^ws1#rvgvq
      - DB_ENGINE=postgresql
      - DB_NAME=happytails
      - DB_USER=happytails
      - DB_PASSWORD=happytails123
      - DB_HOST=postgres
      - DB_PORT=5432
      - OIDC_RP_CLIENT_ID=project-client
      - OIDC_RP_CLIENT_SECRET=QUMf2W089NKFq4UaykDkL9gAuH9H36Ke
      - OIDC_OP_AUTHORIZATION_ENDPOINT=http://localhost:8080/realms/project-realm/protocol/openid-connect/auth
      - OIDC_OP_TOKEN_ENDPOINT=http://keycloak:8080/realms/project-realm/protocol/openid-connect/token
      - OIDC_OP_USER_ENDPOINT=http://keycloak:8080/realms/project-realm/protocol/openid-connect/userinfo
      - OIDC_OP_JWKS_ENDPOINT=http://keycloak:8080/realms/project-realm/protocol/openid-connect/certs
      - OIDC_OP_LOGOUT_ENDPOINT=http://localhost:8080/realms/project-realm/protocol/openid-connect/logout
    networks:
      - happytails-network
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
      - keycloak

networks:
  happytails-network:
    driver: overlay
    attachable: true

volumes:
  postgres-data-new:

configs:
  db_init_script:
    file: ./init-databases.sh